class DatabaseAlreadyOpenException implements Exception{}
class UnableToGetDocumentsDirectory implements Exception{} 
class DatabaseIsNotOpen implements Exception{}
class CouldNotDeleteUser implements Exception{}
class UserAlreadyExists implements Exception{}
class CouldNotFindUser implements Exception{}
class CouldNotDeletePassword implements Exception{}
class CouldNotFindPassword implements Exception{}
class CouldNotUpdatePassword implements Exception{}